name: Trigger auto deployment for bsky-pds

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bsky-pds-AutoDeployTrigger-81ce365d-cab2-49a8-92aa-510460eb1ed2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BSKYPDS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BSKYPDS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BSKYPDS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BSKYPDS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BSKYPDS_REGISTRY_PASSWORD }}
          containerAppName: bsky-pds
          resourceGroup: rg-bsky
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


